### ISSUE TITLE
Terracotta Tombs and Vine Vault (cave_jungle.yml) structures do not generate above certain Y level

### ISSUE THREAD

**Issue by IamMusavaRibica** [Rearth/Origen#20]
After playing with various world generation settings I successfully generated Vine Vault and Terracotta Tombs sometimes at high Y coordinates. But unfortunately they lack some features or structures as seen below.

I looked at [terracotta_tombs.yml](https://github.com/Rearth/Origen/blob/c01cd79717ed1c1172f615ebedd90db37119ff25/biomes/rearth/variants/terracotta_tombs.yml)  and [cave_jungle.yml](https://github.com/Rearth/Origen/blob/c01cd79717ed1c1172f615ebedd90db37119ff25/biomes/rearth/variants/cave_jungle.yml) but couldn't figure out what to change

I know these biomes are not intended to be generated like this. But I'm just wondering what and where has to be changed to get this to work.
Thank you :)

Images (look at the Y coordinate)
![image](https://github.com/user-attachments/assets/e9b41688-b2f7-4b32-880e-801b8a9a1e22)
![image](https://github.com/user-attachments/assets/07de6bdf-40d5-48b1-b842-5ff07d110d43)
![image](https://github.com/user-attachments/assets/1ae0fd37-cca7-4179-9001-5470508ca77c)
![image](https://github.com/user-attachments/assets/00305e36-3916-43c7-a7db-038ff8b576ef)

**Comment by IamMusavaRibica** [comment]
Thorough research has been done in [a thread in the PolyDev discord](https://discord.com/channels/715448651786485780/1328812019016667166), which fixes Vine Vault and 
TL;DR: need to set
```yaml
  min: $meta.yml:bottom-y
  max: $meta.yml:top-y
```
in the `range` option in:
- grass_caves.yml
- large_leaf_vines_underground.yml
- large_ceiling_vines_cave.yml
- crossing_vines_cave.yml

and changing the `locator` in `sinkhole_jungle_trees.yml` to:
```yaml
locator:
  type: AND
  locators:
    - type: PATTERN
      range: &range
        min: $meta.yml:bottom-y
        max: $meta.yml:top-y
      pattern:
        type: MATCH_SET
        blocks: $features/vegetation/meta.yml:plantable-blocks
        offset: -1
    - type: PATTERN
      range: *range
      pattern:
        type: MATCH_SET
        blocks:
          - minecraft:snow
          - minecraft:air
        offset: 0
```

The terracotta tombs are slightly more complicated though that's why I'm not closing this issue (yet)

Thanks RogueShade for assisting me with this!
